// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxdsedynggwaxwmnjfqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4ZHNlZHluZ2d3YXh3bW5qZnFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMzUzNjAsImV4cCI6MjA3MzgxMTM2MH0.r4WAj3cB9hnqD4J2vG3sh9wgCNApTMSWOKWvWbLmzxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});